---
# Play 1: Récupération des outputs Terraform et création de l'inventaire dynamique
- name: Setup from Terraform outputs
  hosts: localhost
  gather_facts: no
  vars:
    terraform_stack_id: "test"
  tasks:
    - name: Get Terraform outputs via spacectl
      shell: spacectl stack output --id={{ terraform_stack_id }} --format=json
      register: terraform_outputs_raw
      check_mode: no

    - name: Parse Terraform outputs
      set_fact:
        terraform_outputs: "{{ terraform_outputs_raw.stdout | from_json }}"
      when: terraform_outputs_raw.stdout != ""

    - name: Extract IPs and endpoints
      set_fact:
        web_ip: "{{ terraform_outputs.web_instance_ip.value }}"
        app_ip: "{{ terraform_outputs.app_instance_ip.value }}"
        db_endpoint: "{{ terraform_outputs.database_endpoint.value }}"
        ssh_private_key: "{{ terraform_outputs.ssh_private_key.value }}"
      when: terraform_outputs is defined

    - name: Create SSH key file
      copy:
        content: "{{ ssh_private_key }}"
        dest: /tmp/ssh_key.pem
        mode: '0600'
      when: ssh_private_key is defined

    - name: Create dynamic inventory
      copy:
        content: |
          [web]
          {{ web_ip }}
          
          [app]
          {{ app_ip }}
          
          [db]
          {{ db_endpoint }}
          
          [all:vars]
          ansible_user=ec2-user
          ansible_ssh_private_key_file=/tmp/ssh_key.pem
          database_endpoint={{ db_endpoint }}
          database_name=webappdb
          database_user=admin
          database_password=Password123!
        dest: ./dynamic_inventory.yml
      when: web_ip is defined and app_ip is defined

    - name: Wait for instances to be SSH ready
      wait_for:
        host: "{{ item }}"
        port: 22
        delay: 10
        timeout: 300
      loop:
        - "{{ web_ip }}"
        - "{{ app_ip }}"
      when: web_ip is defined and app_ip is defined

    - name: Add hosts to in-memory inventory
      add_host:
        name: "{{ item.name }}"
        ansible_host: "{{ item.ip }}"
        groups: "{{ item.group }}"
        ansible_user: ec2-user
        ansible_ssh_private_key_file: /tmp/ssh_key.pem
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      loop:
        - { name: "web_server", ip: "{{ web_ip }}", group: "web" }
        - { name: "app_server", ip: "{{ app_ip }}", group: "app" }
      when: web_ip is defined and app_ip is defined

# Play 2: Configuration 3-Tier AWS (Web + App tiers)
- name: Configuration 3-Tier AWS (Web + App tiers)
  hosts: web,app
  become: yes
  become_method: sudo
  vars:
    repo_url: https://github.com/aws-samples/aws-three-tier-web-architecture-workshop.git
    dest_dir: /opt/aws-three-tier
    app_port: 4000
    web_tier_path: "{{ dest_dir }}/application-code/web-tier"
    app_tier_path: "{{ dest_dir }}/application-code/app-tier"
    app_server_ip: "{{ hostvars[groups['app'][0]]['ansible_host'] | default('localhost') }}"
    database_endpoint: "{{ hostvars['localhost']['db_endpoint'] }}"
    database_name: "webappdb"
    database_user: "admin"
    database_password: "Password123!"

  tasks:
    # ======================
    # CONFIGURATION COMMUNE
    # ======================
    - name: Attendre que les instances soient prêtes
      wait_for_connection:
        delay: 10
        timeout: 300

    - name: Installer les paquets de base
      ansible.builtin.package:
        name:
          - git
          - curl
          - unzip
          - htop
          - python3
          - python3-pip
        state: present

    - name: Créer l'utilisateur pour l'application
      ansible.builtin.user:
        name: appuser
        shell: /bin/bash
        home: /home/appuser
        create_home: yes

    - name: Créer l'utilisateur admin
      ansible.builtin.user:
        name: admin
        shell: /bin/bash
        home: /home/admin
        create_home: yes

    - name: Cloner le repository AWS 3-tier
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_dir }}"
        version: main
        force: yes

    - name: Ajuster les permissions du dossier
      ansible.builtin.file:
        path: "{{ dest_dir }}"
        owner: appuser
        group: appuser
        recurse: yes

    # =================
    # TIER WEB (NGINX)
    # =================
    - block:
      - name: Installer Nginx
        ansible.builtin.package:
          name: nginx
          state: present

      - name: Installer Node.js et npm pour build React (RedHat/CentOS/Amazon Linux)
        ansible.builtin.shell: |
          curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
          yum install -y nodejs
        when: ansible_os_family == "RedHat"

      - name: Installer Node.js et npm (Ubuntu/Debian)
        ansible.builtin.package:
          name:
            - nodejs
            - npm
          state: present
        when: ansible_os_family == "Debian"

      - name: Créer le dossier build pour React
        ansible.builtin.file:
          path: /home/admin/web-tier
          state: directory
          owner: admin
          group: admin
          mode: '0755'

      - name: Vérifier l'existence du dossier web-tier
        ansible.builtin.stat:
          path: "{{ web_tier_path }}"
        register: web_tier_dir

      - name: Installer les dépendances React
        ansible.builtin.shell: |
          cd {{ web_tier_path }}
          npm install --production
        when: web_tier_dir.stat.exists

      - name: Construire l'application React
        ansible.builtin.shell: |
          cd {{ web_tier_path }}
          npm run build
        when: web_tier_dir.stat.exists

      - name: Copier les fichiers build vers le dossier web
        ansible.builtin.copy:
          src: "{{ web_tier_path }}/build/"
          dest: /home/admin/web-tier/build/
          remote_src: yes
          owner: admin
          group: admin
          mode: '0755'
        when: web_tier_dir.stat.exists

      - name: Create nginx configuration template
        copy:
          content: |
            events { worker_connections 1024; }
            http {
                include /etc/nginx/mime.types;
                default_type application/octet-stream;
                server {
                    listen 80;
                    location / {
                        root /home/admin/web-tier/build;
                        try_files $uri $uri/ /index.html;
                    }
                    location /api/ {
                        proxy_pass http://{{ app_server_ip }}:4000/;
                        proxy_set_header Host $host;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    }
                }
            }
          dest: /etc/nginx/nginx.conf
          backup: yes
        notify: restart nginx

      - name: Corriger les permissions pour nginx - dossiers parents
        ansible.builtin.file:
          path: "{{ item }}"
          mode: 'o+x'
        loop:
          - /home
          - /home/admin

      - name: Corriger les permissions pour nginx - dossier web-tier
        ansible.builtin.file:
          path: /home/admin/web-tier/build
          mode: 'o+rX'
          recurse: yes

      - name: Démarrer et activer Nginx
        ansible.builtin.service:
          name: nginx
          state: started
          enabled: yes

      when: "'web' in group_names"

    # ========================
    # TIER APPLICATION (NODE)
    # ========================
    - block:
      - name: Installer Node.js et npm pour app tier (RedHat/CentOS/Amazon Linux)
        ansible.builtin.shell: |
          curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
          yum install -y nodejs
        when: ansible_os_family == "RedHat"

      - name: Installer Node.js et npm (Ubuntu/Debian)
        ansible.builtin.package:
          name:
            - nodejs
            - npm
          state: present
        when: ansible_os_family == "Debian"

      - name: Installer PM2 globalement
        ansible.builtin.npm:
          name: pm2
          global: yes

      - name: Vérifier l'existence du dossier app-tier
        ansible.builtin.stat:
          path: "{{ app_tier_path }}"
        register: app_tier_dir

      - name: Installer les dépendances de l'application
        ansible.builtin.shell: |
          cd {{ app_tier_path }}
          npm install --production
        when: app_tier_dir.stat.exists

      - name: Create app environment file
        copy:
          content: |
            DB_HOST={{ database_endpoint }}
            DB_NAME={{ database_name }}
            DB_USER={{ database_user }}
            DB_PASSWORD={{ database_password }}
            PORT=4000
          dest: "{{ app_tier_path }}/.env"
          owner: appuser
          group: appuser
          mode: '0644'

      - name: Arrêter les anciens processus PM2
        ansible.builtin.shell: pm2 kill
        ignore_errors: yes
        become_user: appuser

      - name: Démarrer l'application avec PM2
        ansible.builtin.shell: |
          cd {{ app_tier_path }}
          pm2 start index.js --name "three-tier-app"
          pm2 save
        become_user: appuser
        when: app_tier_dir.stat.exists

      - name: Configurer PM2 au démarrage
        ansible.builtin.shell: |
          pm2 startup
          pm2 save
        ignore_errors: yes

      when: "'app' in group_names"

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
