---
# Play 1: Setup depuis les variables d'environnement Spacelift
- name: Setup from environment variables
  hosts: localhost
  gather_facts: yes
  connection: local
  tasks:
    - name: Read values from files created by hook
      slurp:
        src: "{{ item.file }}"
      register: ip_files
      loop:
        - { name: "web_ip", file: "/tmp/web_ip.txt" }
        - { name: "app_ip", file: "/tmp/app_ip.txt" }
        - { name: "db_endpoint", file: "/tmp/db_endpoint.txt" }

    - name: Set facts from file content
      set_fact:
        web_ip: "{{ (ip_files.results | selectattr('item.name', 'equalto', 'web_ip') | first).content | b64decode | trim }}"
        app_ip: "{{ (ip_files.results | selectattr('item.name', 'equalto', 'app_ip') | first).content | b64decode | trim }}"
        db_endpoint: "{{ (ip_files.results | selectattr('item.name', 'equalto', 'db_endpoint') | first).content | b64decode | trim }}"

    - name: Debug - Show values from hook
      debug:
        msg:
          - "WEB_IP: {{ web_ip }}"
          - "APP_IP: {{ app_ip }}"
          - "DB_ENDPOINT: {{ db_endpoint }}"

    - name: Check if SSH key file exists
      stat:
        path: /tmp/ssh_key.pem
      register: ssh_key_stat

    - name: Debug - SSH key status
      debug:
        msg: "SSH key file exists: {{ ssh_key_stat.stat.exists }}"

    - name: Add hosts to inventory
      add_host:
        name: "{{ item.name }}"
        ansible_host: "{{ item.ip }}"
        groups: "{{ item.group }}"
        ansible_user: ec2-user
        ansible_ssh_private_key_file: /tmp/ssh_key.pem
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      loop:
        - { name: "web_server", ip: "{{ web_ip }}", group: "web" }
        - { name: "app_server", ip: "{{ app_ip }}", group: "app" }

# Play 2: Configuration 3-Tier AWS (Web + App tiers)
- name: Configuration 3-Tier AWS (Web + App tiers)
  hosts: web,app
  become: yes
  become_method: sudo
  vars:
    repo_url: https://github.com/aws-samples/aws-three-tier-web-architecture-workshop.git
    dest_dir: /opt/aws-three-tier
    app_port: 4000
    web_tier_path: "{{ dest_dir }}/application-code/web-tier"
    app_tier_path: "{{ dest_dir }}/application-code/app-tier"
    app_server_ip: "{{ hostvars['app_server']['ansible_host'] }}"
    database_endpoint: "{{ hostvars['localhost']['db_endpoint'] }}"
    database_name: "webappdb"
    database_user: "admin"
    database_password: "Password123!"

  tasks:
    # ======================
    # CONFIGURATION COMMUNE
    # ======================
    - name: Attendre que les instances soient prêtes
      wait_for_connection:
        delay: 10
        timeout: 300

    - name: Installer les paquets de base
      ansible.builtin.package:
        name:
          - git
          - curl
          - unzip
          - htop
          - python3
          - python3-pip
        state: present

    - name: Créer l'utilisateur pour l'application
      ansible.builtin.user:
        name: appuser
        shell: /bin/bash
        home: /home/appuser
        create_home: yes
        state: present

    - name: Créer l'utilisateur admin
      ansible.builtin.user:
        name: admin
        shell: /bin/bash
        home: /home/admin
        create_home: yes
        state: present

    - name: Ensure user directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ item.split('/')[-1] }}"
        group: "{{ item.split('/')[-1] }}"
        mode: '0755'
      loop:
        - /home/appuser
        - /home/admin

    - name: Cloner le repository AWS 3-tier
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_dir }}"
        version: main
        force: yes

    - name: Vérifier la structure du repository
      ansible.builtin.find:
        paths: "{{ dest_dir }}"
        file_type: directory
        recurse: no
      register: repo_structure

    - name: Afficher la structure du repository
      ansible.builtin.debug:
        var: repo_structure.files

    - name: Ajuster les permissions du dossier
      ansible.builtin.file:
        path: "{{ dest_dir }}"
        owner: appuser
        group: appuser
        recurse: yes

    # =================
    # TIER WEB (NGINX)
    # =================
    - block:
      # Installation spécifique nginx pour Amazon Linux avec plusieurs fallbacks
      - name: Try EPEL repository installation (Amazon Linux)
        ansible.builtin.shell: |
          amazon-linux-extras install epel -y
        ignore_errors: yes

      - name: Try nginx installation via amazon-linux-extras
        ansible.builtin.shell: |
          amazon-linux-extras install nginx1 -y
        ignore_errors: yes

      - name: Try nginx installation via package manager
        ansible.builtin.package:
          name: nginx
          state: present
        ignore_errors: yes

      - name: Check if nginx is installed
        ansible.builtin.command: which nginx
        register: nginx_check
        ignore_errors: yes

      # Fallback: install nginx from source for Amazon Linux
      - name: Install nginx from source (Amazon Linux fallback)
        block:
          - name: Install build dependencies
            ansible.builtin.package:
              name:
                - gcc
                - gcc-c++
                - make
                - zlib-devel
                - pcre-devel
                - openssl-devel
                - wget
              state: present

          - name: Download nginx source
            ansible.builtin.get_url:
              url: http://nginx.org/download/nginx-1.20.2.tar.gz
              dest: /tmp/nginx-1.20.2.tar.gz
              mode: '0644'

          - name: Extract nginx source
            ansible.builtin.unarchive:
              src: /tmp/nginx-1.20.2.tar.gz
              dest: /tmp/
              remote_src: yes

          - name: Create nginx user
            ansible.builtin.user:
              name: nginx
              system: yes
              shell: /bin/false
              home: /var/cache/nginx
              create_home: no

          - name: Create nginx directories
            ansible.builtin.file:
              path: "{{ item }}"
              state: directory
              owner: nginx
              group: nginx
              mode: '0755'
            loop:
              - /var/cache/nginx
              - /var/log/nginx
              - /etc/nginx/conf.d

          - name: Compile and install nginx
            ansible.builtin.shell: |
              cd /tmp/nginx-1.20.2
              ./configure \
                --prefix=/etc/nginx \
                --sbin-path=/usr/sbin/nginx \
                --modules-path=/usr/lib64/nginx/modules \
                --conf-path=/etc/nginx/nginx.conf \
                --error-log-path=/var/log/nginx/error.log \
                --http-log-path=/var/log/nginx/access.log \
                --pid-path=/var/run/nginx.pid \
                --lock-path=/var/run/nginx.lock \
                --http-client-body-temp-path=/var/cache/nginx/client_temp \
                --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
                --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
                --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
                --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
                --user=nginx \
                --group=nginx \
                --with-compat \
                --with-file-aio \
                --with-threads \
                --with-http_addition_module \
                --with-http_auth_request_module \
                --with-http_dav_module \
                --with-http_flv_module \
                --with-http_gunzip_module \
                --with-http_gzip_static_module \
                --with-http_mp4_module \
                --with-http_random_index_module \
                --with-http_realip_module \
                --with-http_secure_link_module \
                --with-http_slice_module \
                --with-http_ssl_module \
                --with-http_stub_status_module \
                --with-http_sub_module \
                --with-http_v2_module \
                --with-stream \
                --with-stream_realip_module \
                --with-stream_ssl_module \
                --with-stream_ssl_preread_module
              make -j$(nproc)
              make install

          - name: Create basic nginx.conf for mime types
            ansible.builtin.copy:
              content: |
                include /etc/nginx/mime.types;
                default_type application/octet-stream;
              dest: /etc/nginx/mime.types
              backup: no

          - name: Download mime.types
            ansible.builtin.get_url:
              url: https://raw.githubusercontent.com/nginx/nginx/master/conf/mime.types
              dest: /etc/nginx/mime.types
              mode: '0644'
              backup: no

          - name: Create nginx systemd service
            ansible.builtin.copy:
              content: |
                [Unit]
                Description=The nginx HTTP and reverse proxy server
                After=network.target remote-fs.target nss-lookup.target

                [Service]
                Type=forking
                PIDFile=/var/run/nginx.pid
                ExecStartPre=/usr/sbin/nginx -t
                ExecStart=/usr/sbin/nginx
                ExecReload=/bin/kill -s HUP $MAINPID
                ExecStop=/bin/kill -s QUIT $MAINPID
                KillSignal=SIGQUIT
                TimeoutStopSec=5
                KillMode=mixed
                PrivateTmp=true

                [Install]
                WantedBy=multi-user.target
              dest: /etc/systemd/system/nginx.service

          - name: Reload systemd daemon
            ansible.builtin.systemd:
              daemon_reload: yes


      # Install Node.js BEFORE trying to use npm
      - name: Install Node.js and npm pour build React (Amazon Linux)
        ansible.builtin.shell: |
          curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
          yum install -y nodejs

      - name: Install Node.js and npm (Ubuntu/Debian)
        ansible.builtin.package:
          name:
            - nodejs
            - npm
          state: present

      - name: Verify Node.js installation
        ansible.builtin.shell: |
          node --version
          npm --version
        register: node_version
        ignore_errors: yes

      - name: Debug Node.js version
        debug:
          var: node_version.stdout_lines

      - name: Créer le dossier build pour React
        ansible.builtin.file:
          path: /home/admin/web-tier
          state: directory
          owner: admin
          group: admin
          mode: '0755'

      - name: Vérifier l'existence du dossier web-tier
        ansible.builtin.stat:
          path: "{{ web_tier_path }}"
        register: web_tier_dir

      - name: Afficher le chemin du web-tier
        ansible.builtin.debug:
          msg: "Web tier path: {{ web_tier_path }}, exists: {{ web_tier_dir.stat.exists }}"

      - name: Installer les dépendances React
        ansible.builtin.shell: |
          cd {{ web_tier_path }}
          npm install
        become_user: admin

      - name: Construire l'application React
        ansible.builtin.shell: |
          cd {{ web_tier_path }}
          npm run build
        become_user: admin

      - name: Copier les fichiers build vers le dossier web
        ansible.builtin.copy:
          src: "{{ web_tier_path }}/build/"
          dest: /home/admin/web-tier/build/
          remote_src: yes
          owner: admin
          group: admin
          mode: '0755'

      - name: Configurer Nginx avec le template
        ansible.builtin.template:
          src: nginx.conf.j2
          dest: /etc/nginx/nginx.conf
          backup: yes
        notify: restart nginx

      - name: Corriger les permissions pour nginx - dossiers parents
        ansible.builtin.file:
          path: "{{ item }}"
          mode: 'o+x'
        loop:
          - /home
          - /home/admin

      - name: Corriger les permissions pour nginx - dossier web-tier
        ansible.builtin.file:
          path: /home/admin/web-tier/build
          mode: 'o+rX'
          recurse: yes

      - name: Démarrer et activer Nginx
        ansible.builtin.service:
          name: nginx
          state: started
          enabled: yes


    # ========================
    # TIER APPLICATION (NODE)
    # ========================
    - block:
      - name: Install Node.js et npm pour app tier (Amazon Linux)
        ansible.builtin.shell: |
          curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
          yum install -y nodejs

      - name: Install Node.js and npm (Ubuntu/Debian)
        ansible.builtin.package:
          name:
            - nodejs
            - npm
          state: present

      - name: Verify Node.js and npm installation
        ansible.builtin.shell: |
          node --version
          npm --version
        register: node_version_app
        ignore_errors: yes

      - name: Debug Node.js version on app server
        debug:
          var: node_version_app.stdout_lines

      - name: Install PM2 globalement
        ansible.builtin.npm:
          name: pm2
          global: yes

      - name: Vérifier le contenu du dossier app-tier
        ansible.builtin.find:
          paths: "{{ app_tier_path }}"
          patterns: "*"
        register: app_tier_files

      - name: Afficher les fichiers trouvés dans app-tier
        ansible.builtin.debug:
          var: app_tier_files.files

      - name: Installer les dépendances de l'application
        ansible.builtin.shell: |
          cd {{ app_tier_path }}
          npm install
        become_user: appuser

      - name: Create app environment file
        ansible.builtin.copy:
          content: |
            DB_HOST={{ database_endpoint.split(':')[0] }}
            DB_NAME={{ database_name }}
            DB_USER={{ database_user }}
            DB_PASSWORD={{ database_password }}
            PORT={{ app_port }}
          dest: "{{ app_tier_path }}/.env"
          owner: appuser
          group: appuser
          mode: '0644'

      - name: Arrêter les anciens processus PM2
        ansible.builtin.shell: pm2 kill
        ignore_errors: yes
        become_user: appuser

      - name: Démarrer l'application avec PM2
        ansible.builtin.shell: |
          cd {{ app_tier_path }}
          pm2 start index.js --name "three-tier-app"
          pm2 save
        become_user: appuser

      - name: Configurer PM2 au démarrage
        ansible.builtin.shell: |
          pm2 startup
          pm2 save
        ignore_errors: yes
        become_user: appuser

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
