---
# Play 1: Setup depuis les variables d'environnement Spacelift
- name: Setup from environment variables
  hosts: localhost
  gather_facts: yes
  connection: local
  tasks:
    - name: Read values from files created by hook
      slurp:
        src: "{{ item.file }}"
      register: ip_files
      loop:
        - { name: "web_ip", file: "/tmp/web_ip.txt" }
        - { name: "app_ip", file: "/tmp/app_ip.txt" }
        - { name: "db_endpoint", file: "/tmp/db_endpoint.txt" }

    - name: Set facts from file content
      set_fact:
        web_ip: "{{ (ip_files.results | selectattr('item.name', 'equalto', 'web_ip') | first).content | b64decode | trim }}"
        app_ip: "{{ (ip_files.results | selectattr('item.name', 'equalto', 'app_ip') | first).content | b64decode | trim }}"
        db_endpoint: "{{ (ip_files.results | selectattr('item.name', 'equalto', 'db_endpoint') | first).content | b64decode | trim }}"

    - name: Debug - Show values from hook
      debug:
        msg:
          - "WEB_IP: {{ web_ip }}"
          - "APP_IP: {{ app_ip }}"
          - "DB_ENDPOINT: {{ db_endpoint }}"

    - name: Check if SSH key file exists
      stat:
        path: /tmp/ssh_key.pem
      register: ssh_key_stat

    - name: Debug - SSH key status
      debug:
        msg: "SSH key file exists: {{ ssh_key_stat.stat.exists }}"

    - name: Add hosts to inventory
      add_host:
        name: "{{ item.name }}"
        ansible_host: "{{ item.ip }}"
        groups: "{{ item.group }}"
        ansible_user: ec2-user
        ansible_ssh_private_key_file: /tmp/ssh_key.pem
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      loop:
        - { name: "web_server", ip: "{{ web_ip }}", group: "web" }
        - { name: "app_server", ip: "{{ app_ip }}", group: "app" }

# Play 2: Configuration 3-Tier AWS (Web + App tiers)
- name: Configuration 3-Tier AWS (Web + App tiers)
  hosts: web,app
  become: yes
  become_method: sudo
  vars:
    repo_url: https://github.com/aws-samples/aws-three-tier-web-architecture-workshop.git
    dest_dir: /opt/aws-three-tier
    app_port: 4000
    web_tier_path: "{{ dest_dir }}/application-code/web-tier"
    app_tier_path: "{{ dest_dir }}/application-code/app-tier"
    app_server_ip: "{{ hostvars['app_server']['ansible_host'] }}"
    database_endpoint: "{{ hostvars['localhost']['db_endpoint'] }}"
    database_name: "webappdb"
    database_user: "admin"
    database_password: "Password123!"

  tasks:
    # ======================
    # CONFIGURATION COMMUNE
    # ======================
    - name: Attendre que les instances soient prêtes
      wait_for_connection:
        delay: 10
        timeout: 300

    - name: Installer les paquets de base
      ansible.builtin.package:
        name:
          - git
          - curl
          - unzip
          - htop
          - python3
          - python3-pip
        state: present

    - name: Créer l'utilisateur pour l'application
      ansible.builtin.user:
        name: appuser
        shell: /bin/bash
        home: /home/appuser
        create_home: yes

    - name: Créer l'utilisateur admin
      ansible.builtin.user:
        name: admin
        shell: /bin/bash
        home: /home/admin
        create_home: yes

    - name: Cloner le repository AWS 3-tier
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_dir }}"
        version: main
        force: yes

    - name: Ajuster les permissions du dossier
      ansible.builtin.file:
        path: "{{ dest_dir }}"
        owner: appuser
        group: appuser
        recurse: yes

    # =================
    # TIER WEB (NGINX)
    # =================
    - block:
      # Fix for Amazon Linux - Enable EPEL and install nginx
      - name: Install EPEL repository (Amazon Linux)
        ansible.builtin.shell: |
          amazon-linux-extras install epel -y
        when: ansible_os_family == "RedHat" and ansible_distribution == "Amazon"
        ignore_errors: yes

      - name: Alternative nginx installation for Amazon Linux
        ansible.builtin.shell: |
          amazon-linux-extras install nginx1 -y
        when: ansible_os_family == "RedHat" and ansible_distribution == "Amazon"
        ignore_errors: yes

      - name: Installer Nginx (standard)
        ansible.builtin.package:
          name: nginx
          state: present
        ignore_errors: yes

      - name: Verify nginx installation
        ansible.builtin.shell: which nginx
        register: nginx_check
        ignore_errors: yes

      - name: Install nginx from source if package failed (Amazon Linux fallback)
        block:
          - name: Install compilation dependencies
            ansible.builtin.package:
              name:
                - gcc
                - gcc-c++
                - make
                - zlib-devel
                - pcre-devel
                - openssl-devel
              state: present

          - name: Download nginx source
            ansible.builtin.get_url:
              url: http://nginx.org/download/nginx-1.20.2.tar.gz
              dest: /tmp/nginx-1.20.2.tar.gz

          - name: Extract nginx source
            ansible.builtin.unarchive:
              src: /tmp/nginx-1.20.2.tar.gz
              dest: /tmp/
              remote_src: yes

          - name: Compile and install nginx
            ansible.builtin.shell: |
              cd /tmp/nginx-1.20.2
              ./configure --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock
              make && make install

          - name: Create nginx service file
            ansible.builtin.copy:
              content: |
                [Unit]
                Description=nginx HTTP Server
                After=network.target

                [Service]
                Type=forking
                PIDFile=/var/run/nginx.pid
                ExecStartPre=/usr/sbin/nginx -t
                ExecStart=/usr/sbin/nginx
                ExecReload=/bin/kill -s HUP $MAINPID
                ExecStop=/bin/kill -s QUIT $MAINPID
                PrivateTmp=true

                [Install]
                WantedBy=multi-user.target
              dest: /etc/systemd/system/nginx.service

          - name: Reload systemd
            ansible.builtin.systemd:
              daemon_reload: yes

        when: nginx_check.rc != 0

      # Install Node.js BEFORE trying to use npm
      - name: Install Node.js and npm (RedHat/CentOS/Amazon Linux)
        ansible.builtin.shell: |
          curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
          yum install -y nodejs
        when: ansible_os_family == "RedHat"

      - name: Install Node.js and npm (Ubuntu/Debian)
        ansible.builtin.package:
          name:
            - nodejs
            - npm
          state: present
        when: ansible_os_family == "Debian"

      - name: Verify Node.js installation
        ansible.builtin.shell: |
          node --version
          npm --version
        register: node_version

      - name: Debug Node.js version
        debug:
          var: node_version.stdout_lines

      - name: Créer le dossier build pour React
        ansible.builtin.file:
          path: /home/admin/web-tier
          state: directory
          owner: admin
          group: admin
          mode: '0755'

      - name: Vérifier l'existence du dossier web-tier
        ansible.builtin.stat:
          path: "{{ web_tier_path }}"
        register: web_tier_dir

      - name: Installer les dépendances React
        ansible.builtin.shell: |
          cd {{ web_tier_path }}
          npm install --production
        when: web_tier_dir.stat.exists
        become_user: admin

      - name: Construire l'application React
        ansible.builtin.shell: |
          cd {{ web_tier_path }}
          npm run build
        when: web_tier_dir.stat.exists
        become_user: admin

      - name: Copier les fichiers build vers le dossier web
        ansible.builtin.copy:
          src: "{{ web_tier_path }}/build/"
          dest: /home/admin/web-tier/build/
          remote_src: yes
          owner: admin
          group: admin
          mode: '0755'
        when: web_tier_dir.stat.exists

      - name: Create nginx configuration from template
        template:
          src: nginx.conf.j2
          dest: /etc/nginx/nginx.conf
          backup: yes
        notify: restart nginx

      - name: Create nginx directories
        ansible.builtin.file:
          path: "{{ item }}"
          state: directory
          mode: '0755'
        loop:
          - /var/log/nginx
          - /etc/nginx

      - name: Corriger les permissions pour nginx - dossiers parents
        ansible.builtin.file:
          path: "{{ item }}"
          mode: 'o+x'
        loop:
          - /home
          - /home/admin

      - name: Corriger les permissions pour nginx - dossier web-tier
        ansible.builtin.file:
          path: /home/admin/web-tier/build
          mode: 'o+rX'
          recurse: yes
        when: web_tier_dir.stat.exists

      - name: Démarrer et activer Nginx
        ansible.builtin.service:
          name: nginx
          state: started
          enabled: yes

      when: "'web' in group_names"

    # ========================
    # TIER APPLICATION (NODE)
    # ========================
    - block:
      # Install Node.js FIRST, before trying to use npm
      - name: Install Node.js and npm for app tier (RedHat/CentOS/Amazon Linux)
        ansible.builtin.shell: |
          curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
          yum install -y nodejs
        when: ansible_os_family == "RedHat"

      - name: Install Node.js and npm (Ubuntu/Debian)
        ansible.builtin.package:
          name:
            - nodejs
            - npm
          state: present
        when: ansible_os_family == "Debian"

      - name: Verify Node.js and npm installation
        ansible.builtin.shell: |
          node --version
          npm --version
        register: node_version_app

      - name: Debug Node.js version on app server
        debug:
          var: node_version_app.stdout_lines

      - name: Install PM2 globally
        ansible.builtin.npm:
          name: pm2
          global: yes

      - name: Vérifier l'existence du dossier app-tier
        ansible.builtin.stat:
          path: "{{ app_tier_path }}"
        register: app_tier_dir

      - name: Install application dependencies
        ansible.builtin.shell: |
          cd {{ app_tier_path }}
          npm install --production
        when: app_tier_dir.stat.exists
        become_user: appuser

      - name: Create app environment file
        copy:
          content: |
            DB_HOST={{ database_endpoint }}
            DB_NAME={{ database_name }}
            DB_USER={{ database_user }}
            DB_PASSWORD={{ database_password }}
            PORT=4000
          dest: "{{ app_tier_path }}/.env"
          owner: appuser
          group: appuser
          mode: '0644'

      - name: Stop old PM2 processes
        ansible.builtin.shell: pm2 kill
        ignore_errors: yes
        become_user: appuser

      - name: Start application with PM2
        ansible.builtin.shell: |
          cd {{ app_tier_path }}
          pm2 start index.js --name "three-tier-app"
          pm2 save
        become_user: appuser
        when: app_tier_dir.stat.exists

      - name: Configure PM2 for startup
        ansible.builtin.shell: |
          pm2 startup
          pm2 save
        ignore_errors: yes

      when: "'app' in group_names"

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
